route:
  group_by: [Alertname]
  # Send all notifications to me.
  receiver: email-me

receivers:
- name: email-me
  email_configs:
  - to: sarba.jit.das433@gmail.com
    from: testingforjenkins@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: testingforjenkins@gmail.com
    auth_identity: testingforjenkins@gmail.com
    auth_password: Jenkins@2021
    send_resolved: true
