version: '3.1'

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
  prometheus:
    image: 'prom/prometheus:latest'
    container_name: prometheus
    volumes:
    - ./prometheus:/etc/prometheus:ro
    - prometheus_data:/prometheus
    #- ./prometheus/rules.yml:/etc/prometheus/rules.yml:ro
    #- ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--storage.tsdb.path=/prometheus'
    - '--storage.tsdb.retention.time=100h'
    #- '--web.console.libraries=/etc/prometheus/console_libraries'
    #- '--web.console.templates=/etc/prometheus/consoles'
    #- '--web.enable-lifecycle'
    ports:
    - '9090:9090'
    network_mode: bridge
    restart: unless-stopped
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager_Mail.yml'
      - '--storage.path=/alertmanager'
    ports:
      - 9093:9093
    network_mode: bridge
    restart: unless-stopped
  cadvisor:
    image: 'google/cadvisor:latest'
    container_name: cadvisor
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:ro
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    - /dev/disk:/dev/disk/:ro
    ports:
    - '15015:8080'
    network_mode: bridge
    restart: unless-stopped
  node-exporter:
    image: prom/node-exporter
    container_name: PROM_NODE_EXP
    command:
    - '--path.rootfs=/host'
    volumes:
    - /:/host:ro,rslave
    ports:
    - '9100:9100'
    pid: host
    network_mode: bridge
    restart: unless-stopped
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./grafana/conf/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./grafana/conf/provisioning:/etc/grafana/provisioning:ro
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
    - '12290:3000'
    network_mode: bridge
    restart: unless-stopped
