global:
  scrape_interval: 30s
rule_files:
- 'alert.yml'
alerting:
  alertmanagers:
  - static_configs:
    - targets:
    # whatever you want
      - '192.168.56.88:9093'
scrape_configs:
- job_name: 'tomcat'
  scrape_interval: 40s
  static_configs:
  - targets: ['192.168.56.88:6060']
    labels: 
      alias: 'tomcat-deployment-container'
- job_name: 'prometheus'
  static_configs:
  - targets: ['192.168.56.88:9090']
    labels:
      alias: 'prometheus'
- job_name: 'node-exporter'
  static_configs:
   - targets: ['192.168.56.88:9100']
     labels:
       alias: 'node-exporter'
- job_name: 'alertmanager'
  static_configs:
  - targets: ['192.168.56.88:9093']
    labels:
      alias: 'alertmanager'
- job_name: 'cadvisor'
  static_configs:
  - targets: ['192.168.56.88:15015']
    labels:
      alias: 'cadvisor'
